### ISSUE TITLE
Dockerfile for docker image core-cuda-focal

### ISSUE THREAD

**Issue by welaunchcn** [kasmtech/workspaces-core-images#28]
Could you please upload the Dockerfile for building core-cuda-focal docker image?

**Comment by j-travis** [comment]
Hi, we leverage the same dockerfile for multiple builds since they are very similar in some use-cases. You can see the special build flags we use for cuda:
https://github.com/kasmtech/workspaces-core-images/blob/develop/.gitlab-ci.yml#L85

You don't need all the tags but you will need the build args
