### ISSUE TITLE
failed to build (ubuntu core)

### ISSUE THREAD

**Issue by magadan** [kasmtech/workspaces-core-images#5]
failed to build (ubuntu core)

Step 24/68 : ADD ./src/$DISTRO/xfce/.config/ $HOME/.config/
failed to get destination image "sha256:f362d47a001d8ad1edf44e02808bd3c4584cc388a982d0b6b339a85a8d35c282": No such image: sha256:f362d47a001d8ad1edf44e02808bd3c4584cc388a982d0b6b339a85a8d35c282

**Comment by mmcclaskey** [comment]
You need to turn "Automatically Prune Images" to Off in the agent settings, if you want to build images directly on the Kasm Workspaces server. https://kasmweb.com/docs/latest/guide/agent_settings.html?highlight=pruning#agent-settings

By default the server automatically checks for new versions of images (for those that are in a registry) every 1 hour. So if you pointed to our "rolling" images, which are built nightly, your installation would pull updated images every day automatically. Since that results in a lot of old untagged images, the agents automatically delete untagged Kasm Workspace images. Unfortunately, that auto pruning interferes with building images locally. For production use cases, you would want to build custom images in a pipeline and push to a central registry and rely on Kasm Workspaces to automatically pull the image updates down.

**Comment by magadan** [comment]
thank u !
